name: Update Content

on:
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - 'src/a2025_club_world_cup/data/jogos_1afase.csv'
      - 'src/a2025_club_world_cup/data/jogos_playoffs.csv'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: setup python and libs # search version on file '.python-version'
        run: |
          uv python install
          uv sync

      - name: Run update content
        run: |
          python -m src.a2025_club_world_cup.processing.main
          python -m src.a2025_club_world_cup.reports.main

      - run: |
          git config --global user.name adntayer
          git config --global user.email 'adntayer@users.noreply.github.com'
          git commit -am  "score update at ${{ steps.date.outputs.date }}"
          git push
