name: Deploy Page

env:
  DOCS_PATH: src/championships/2026_world_cup/reports/html

on:
  workflow_dispatch:
  schedule:
    # 18:30 UTC / 15:30 Horário de Brasília (Pega os jogos das 13h)
    - cron: '10 18 * * *'
    # 21:30 UTC / 18:30 Horário de Brasília (Pega os jogos das 16h)
    - cron: '10 21 * * *'
    # 04:30 UTC / 01:30 Horário de Brasília (Pega os jogos das 19h e 22h + prorrogações)
    - cron: '10 4 * * *'
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/championships/2026_world_cup/reports/html/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCS_PATH }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
